### PR TITLE
MKL bug workaround

### PR DESCRIPTION
**Pull request by jcapriot**
Will set to default reordering scheme, only if version 11.3.3

### CODE REVIEW

**Comment by dwfmarchant** [comment]
Temporary fix for reordering bug in MKL 11.3.3.

**Comment by rowanc1** [comment]
Can you be sure to bump the version and update pypi? Do you have experience with auto deploy from travis to pypi?
https://docs.travis-ci.com/user/deployment/pypi/
Works well!

Thanks @dwfmarchant, hope all is going swell!

**Comment by dwfmarchant** [comment]
Just trying to figure out how to do that - thanks for the tip!

**Comment by rowanc1** [comment]
Can also do it `after_success`

https://github.com/3ptscience/steno3dpy/blob/master/.travis.yml

Need to `travis encrypt` a file (which adds the first line except the `~/`) if you want a bit more control.

**Comment by dwfmarchant** [comment]
Broke things there for a minute but I think its up and running again at version 0.0.3 again.

**Pull request merged**
